import { createFileRoute, redirect } from "@tanstack/react-router";
import { PageHeader, Panel, Chip } from "@/components/ciap/primitives";
import { Sparkles, Download, Share2, TrendingUp, ShieldAlert, MapPin } from "lucide-react";

export const Route = createFileRoute("/ai-insights")({
  beforeLoad: () => { throw redirect({ to: "/intelligence" }); },
});

export function AIInsights() {
  return (
    <div className="space-y-6">
      <PageHeader eyebrow="AI INSIGHTS" title="Daily Intelligence Briefing"
        description="Natural-language summary generated by CIAP LLM · updated every 15 minutes."
        actions={<div className="flex gap-2">
          <button className="rounded-lg border border-border bg-secondary/40 px-3 py-1.5 text-xs flex items-center gap-1"><Download className="h-3 w-3" />PDF</button>
          <button className="rounded-lg border border-primary/40 bg-primary/10 text-primary px-3 py-1.5 text-xs flex items-center gap-1"><Share2 className="h-3 w-3" />Share</button>
        </div>} />
      <Panel>
        <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.25em] text-primary"><Sparkles className="h-3 w-3" />Executive Summary · Auto-generated</div>
        <p className="mt-3 text-sm leading-relaxed text-foreground/90">
          In the last 24 hours, Karnataka recorded <span className="text-primary font-semibold">312 incidents</span> — a <span className="text-emerald-400">6.1% decline</span> vs the prior day.
          However, <span className="text-destructive font-semibold">cyber-fraud spiked 38%</span> in Mangaluru and a repeat-offender cluster re-emerged along the MG Road corridor.
          The model projects a <span className="text-primary font-semibold">critical armed-robbery window (72h)</span> in central Bengaluru at 87% confidence.
        </p>
      </Panel>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {[
          { i: TrendingUp, t: "Emerging Threats", items: ["Cyber fraud +38% (Mangaluru)", "Vehicle theft ring · KA-05", "Narcotics micro-market · Udupi"] },
          { i: MapPin, t: "Patrol Allocation", items: ["MG Road · +12 units (night)", "Whitefield · +8 units", "Panambur · CAT-B backup"] },
          { i: ShieldAlert, t: "High-Priority Districts", items: ["Bengaluru Urban · risk 92", "Mysuru · risk 74", "Kalaburagi · risk 71"] },
        ].map((s) => (
          <Panel key={s.t} title={s.t} icon={<s.i className="h-4 w-4" />}>
            <ul className="space-y-2 text-sm">
              {s.items.map((it) => (
                <li key={it} className="flex items-center gap-2 rounded-lg border border-border/60 bg-secondary/30 p-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary animate-glow-pulse" />{it}
                </li>
              ))}
            </ul>
          </Panel>
        ))}
      </div>
    </div>
  );
}