/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VictimsRouteImport } from './routes/victims'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SuspectsRouteImport } from './routes/suspects'
import { Route as SociologyRouteImport } from './routes/sociology'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictiveRouteImport } from './routes/predictive'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as HotspotsRouteImport } from './routes/hotspots'
import { Route as DataImportRouteImport } from './routes/data-import'
import { Route as CrimeMapRouteImport } from './routes/crime-map'
import { Route as CrimeAnalyticsRouteImport } from './routes/crime-analytics'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AnomalyRouteImport } from './routes/anomaly'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AdvancedAnalyticsRouteImport } from './routes/advanced-analytics'
import { Route as IndexRouteImport } from './routes/index'

const VictimsRoute = VictimsRouteImport.update({
  id: '/victims',
  path: '/victims',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspectsRoute = SuspectsRouteImport.update({
  id: '/suspects',
  path: '/suspects',
  getParentRoute: () => rootRouteImport,
} as any)
const SociologyRoute = SociologyRouteImport.update({
  id: '/sociology',
  path: '/sociology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveRoute = PredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const HotspotsRoute = HotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const DataImportRoute = DataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const CrimeMapRoute = CrimeMapRouteImport.update({
  id: '/crime-map',
  path: '/crime-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CrimeAnalyticsRoute = CrimeAnalyticsRouteImport.update({
  id: '/crime-analytics',
  path: '/crime-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyRoute = AnomalyRouteImport.update({
  id: '/anomaly',
  path: '/anomaly',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedAnalyticsRoute = AdvancedAnalyticsRouteImport.update({
  id: '/advanced-analytics',
  path: '/advanced-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced-analytics': typeof AdvancedAnalyticsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly': typeof AnomalyRoute
  '/cases': typeof CasesRoute
  '/crime-analytics': typeof CrimeAnalyticsRoute
  '/crime-map': typeof CrimeMapRoute
  '/data-import': typeof DataImportRoute
  '/hotspots': typeof HotspotsRoute
  '/intelligence': typeof IntelligenceRoute
  '/investigation': typeof InvestigationRoute
  '/network': typeof NetworkRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sociology': typeof SociologyRoute
  '/suspects': typeof SuspectsRoute
  '/trends': typeof TrendsRoute
  '/victims': typeof VictimsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced-analytics': typeof AdvancedAnalyticsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly': typeof AnomalyRoute
  '/cases': typeof CasesRoute
  '/crime-analytics': typeof CrimeAnalyticsRoute
  '/crime-map': typeof CrimeMapRoute
  '/data-import': typeof DataImportRoute
  '/hotspots': typeof HotspotsRoute
  '/intelligence': typeof IntelligenceRoute
  '/investigation': typeof InvestigationRoute
  '/network': typeof NetworkRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sociology': typeof SociologyRoute
  '/suspects': typeof SuspectsRoute
  '/trends': typeof TrendsRoute
  '/victims': typeof VictimsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced-analytics': typeof AdvancedAnalyticsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly': typeof AnomalyRoute
  '/cases': typeof CasesRoute
  '/crime-analytics': typeof CrimeAnalyticsRoute
  '/crime-map': typeof CrimeMapRoute
  '/data-import': typeof DataImportRoute
  '/hotspots': typeof HotspotsRoute
  '/intelligence': typeof IntelligenceRoute
  '/investigation': typeof InvestigationRoute
  '/network': typeof NetworkRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sociology': typeof SociologyRoute
  '/suspects': typeof SuspectsRoute
  '/trends': typeof TrendsRoute
  '/victims': typeof VictimsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced-analytics'
    | '/ai-insights'
    | '/anomaly'
    | '/cases'
    | '/crime-analytics'
    | '/crime-map'
    | '/data-import'
    | '/hotspots'
    | '/intelligence'
    | '/investigation'
    | '/network'
    | '/predictive'
    | '/reports'
    | '/settings'
    | '/sociology'
    | '/suspects'
    | '/trends'
    | '/victims'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced-analytics'
    | '/ai-insights'
    | '/anomaly'
    | '/cases'
    | '/crime-analytics'
    | '/crime-map'
    | '/data-import'
    | '/hotspots'
    | '/intelligence'
    | '/investigation'
    | '/network'
    | '/predictive'
    | '/reports'
    | '/settings'
    | '/sociology'
    | '/suspects'
    | '/trends'
    | '/victims'
  id:
    | '__root__'
    | '/'
    | '/advanced-analytics'
    | '/ai-insights'
    | '/anomaly'
    | '/cases'
    | '/crime-analytics'
    | '/crime-map'
    | '/data-import'
    | '/hotspots'
    | '/intelligence'
    | '/investigation'
    | '/network'
    | '/predictive'
    | '/reports'
    | '/settings'
    | '/sociology'
    | '/suspects'
    | '/trends'
    | '/victims'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedAnalyticsRoute: typeof AdvancedAnalyticsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AnomalyRoute: typeof AnomalyRoute
  CasesRoute: typeof CasesRoute
  CrimeAnalyticsRoute: typeof CrimeAnalyticsRoute
  CrimeMapRoute: typeof CrimeMapRoute
  DataImportRoute: typeof DataImportRoute
  HotspotsRoute: typeof HotspotsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  InvestigationRoute: typeof InvestigationRoute
  NetworkRoute: typeof NetworkRoute
  PredictiveRoute: typeof PredictiveRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SociologyRoute: typeof SociologyRoute
  SuspectsRoute: typeof SuspectsRoute
  TrendsRoute: typeof TrendsRoute
  VictimsRoute: typeof VictimsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/victims': {
      id: '/victims'
      path: '/victims'
      fullPath: '/victims'
      preLoaderRoute: typeof VictimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspects': {
      id: '/suspects'
      path: '/suspects'
      fullPath: '/suspects'
      preLoaderRoute: typeof SuspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sociology': {
      id: '/sociology'
      path: '/sociology'
      fullPath: '/sociology'
      preLoaderRoute: typeof SociologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive': {
      id: '/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof PredictiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotspots': {
      id: '/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof HotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-import': {
      id: '/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof DataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crime-map': {
      id: '/crime-map'
      path: '/crime-map'
      fullPath: '/crime-map'
      preLoaderRoute: typeof CrimeMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crime-analytics': {
      id: '/crime-analytics'
      path: '/crime-analytics'
      fullPath: '/crime-analytics'
      preLoaderRoute: typeof CrimeAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly': {
      id: '/anomaly'
      path: '/anomaly'
      fullPath: '/anomaly'
      preLoaderRoute: typeof AnomalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-analytics': {
      id: '/advanced-analytics'
      path: '/advanced-analytics'
      fullPath: '/advanced-analytics'
      preLoaderRoute: typeof AdvancedAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedAnalyticsRoute: AdvancedAnalyticsRoute,
  AiInsightsRoute: AiInsightsRoute,
  AnomalyRoute: AnomalyRoute,
  CasesRoute: CasesRoute,
  CrimeAnalyticsRoute: CrimeAnalyticsRoute,
  CrimeMapRoute: CrimeMapRoute,
  DataImportRoute: DataImportRoute,
  HotspotsRoute: HotspotsRoute,
  IntelligenceRoute: IntelligenceRoute,
  InvestigationRoute: InvestigationRoute,
  NetworkRoute: NetworkRoute,
  PredictiveRoute: PredictiveRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SociologyRoute: SociologyRoute,
  SuspectsRoute: SuspectsRoute,
  TrendsRoute: TrendsRoute,
  VictimsRoute: VictimsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
